# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('cooldown', models.IntegerField(default=300)),
                ('health', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BacteriaBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Block')),
                ('typestr', models.CharField(default='bacteria', max_length=10)),
            ],
            bases=('webapp.block',),
        ),
        migrations.CreateModel(
            name='ColorBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Block')),
                ('color', models.CharField(max_length=10)),
                ('typestr', models.CharField(default='basic', max_length=10)),
            ],
            bases=('webapp.block',),
        ),
        migrations.CreateModel(
            name='GolBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Block')),
                ('gol_cooldown', models.IntegerField()),
                ('typestr', models.CharField(default='gol', max_length=10)),
            ],
            bases=('webapp.block',),
        ),
        migrations.CreateModel(
            name='MbsBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Block')),
                ('mbs_cooldown', models.IntegerField(default=300)),
                ('typestr', models.CharField(default='mbs', max_length=10)),
            ],
            bases=('webapp.block',),
        ),
        migrations.CreateModel(
            name='NotEastBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Block')),
                ('powered', models.BooleanField(default=False)),
                ('typestr', models.CharField(default='note', max_length=10)),
            ],
            bases=('webapp.block',),
        ),
        migrations.CreateModel(
            name='NotNorthBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Block')),
                ('powered', models.BooleanField(default=False)),
                ('typestr', models.CharField(default='notn', max_length=10)),
            ],
            bases=('webapp.block',),
        ),
        migrations.CreateModel(
            name='NotSouthBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Block')),
                ('powered', models.BooleanField(default=False)),
                ('typestr', models.CharField(default='nots', max_length=10)),
            ],
            bases=('webapp.block',),
        ),
        migrations.CreateModel(
            name='NotWestBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Block')),
                ('powered', models.BooleanField(default=False)),
                ('typestr', models.CharField(default='notw', max_length=10)),
            ],
            bases=('webapp.block',),
        ),
        migrations.CreateModel(
            name='OthelloBlackBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Block')),
                ('typestr', models.CharField(default='othb', max_length=10)),
            ],
            bases=('webapp.block',),
        ),
        migrations.CreateModel(
            name='OthelloWhiteBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Block')),
                ('typestr', models.CharField(default='othw', max_length=10)),
            ],
            bases=('webapp.block',),
        ),
        migrations.CreateModel(
            name='TNTBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Block')),
                ('typestr', models.CharField(default='tnt', max_length=10)),
            ],
            bases=('webapp.block',),
        ),
        migrations.CreateModel(
            name='WireBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webapp.Block')),
                ('typestr', models.CharField(default='wireoff', max_length=10)),
            ],
            bases=('webapp.block',),
        ),
    ]
