# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='typestr',
        ),
        migrations.AddField(
            model_name='bacteriablock',
            name='typestr',
            field=models.CharField(default='bacteria', max_length=10),
        ),
        migrations.AddField(
            model_name='colorblock',
            name='typestr',
            field=models.CharField(default='basic', max_length=10),
        ),
        migrations.AddField(
            model_name='golblock',
            name='typestr',
            field=models.CharField(default='gol', max_length=10),
        ),
        migrations.AddField(
            model_name='mbsblock',
            name='typestr',
            field=models.CharField(default='mbs', max_length=10),
        ),
        migrations.AddField(
            model_name='noteastblock',
            name='typestr',
            field=models.CharField(default='note', max_length=10),
        ),
        migrations.AddField(
            model_name='notnorthblock',
            name='typestr',
            field=models.CharField(default='notn', max_length=10),
        ),
        migrations.AddField(
            model_name='notsouthblock',
            name='typestr',
            field=models.CharField(default='nots', max_length=10),
        ),
        migrations.AddField(
            model_name='notwestblock',
            name='typestr',
            field=models.CharField(default='notw', max_length=10),
        ),
        migrations.AddField(
            model_name='othelloblackblock',
            name='typestr',
            field=models.CharField(default='othb', max_length=10),
        ),
        migrations.AddField(
            model_name='othellowhiteblock',
            name='typestr',
            field=models.CharField(default='othw', max_length=10),
        ),
        migrations.AddField(
            model_name='tntblock',
            name='typestr',
            field=models.CharField(default='tnt', max_length=10),
        ),
        migrations.AddField(
            model_name='wireblock',
            name='typestr',
            field=models.CharField(default='wireoff', max_length=10),
        ),
        migrations.AlterField(
            model_name='block',
            name='cooldown',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='block',
            name='health',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='mbsblock',
            name='mbs_cooldown',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='noteastblock',
            name='powered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notnorthblock',
            name='powered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notsouthblock',
            name='powered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notwestblock',
            name='powered',
            field=models.BooleanField(default=False),
        ),
    ]
