# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bacteriablock',
            name='typestr',
        ),
        migrations.RemoveField(
            model_name='colorblock',
            name='typestr',
        ),
        migrations.RemoveField(
            model_name='golblock',
            name='typestr',
        ),
        migrations.RemoveField(
            model_name='mbsblock',
            name='typestr',
        ),
        migrations.RemoveField(
            model_name='noteastblock',
            name='typestr',
        ),
        migrations.RemoveField(
            model_name='notnorthblock',
            name='typestr',
        ),
        migrations.RemoveField(
            model_name='notsouthblock',
            name='typestr',
        ),
        migrations.RemoveField(
            model_name='notwestblock',
            name='typestr',
        ),
        migrations.RemoveField(
            model_name='othelloblackblock',
            name='typestr',
        ),
        migrations.RemoveField(
            model_name='othellowhiteblock',
            name='typestr',
        ),
        migrations.RemoveField(
            model_name='tntblock',
            name='typestr',
        ),
        migrations.RemoveField(
            model_name='wireblock',
            name='typestr',
        ),
        migrations.AddField(
            model_name='wireblock',
            name='powered',
            field=models.BooleanField(default=False),
        ),
    ]
